Repository input-output-hk/io-sim, pull requests merged in 2023-04, with the labels that each got.

#72 Strict MVars without invariant checking
  .github/workflows/cabal.project.local
  .github/workflows/haskell.yml
  .gitignore
  cabal.project
  io-classes/io-classes.cabal
  io-sim/io-sim.cabal
  scripts/check-stylish.sh
  strict-mvar/CHANGELOG.md
  strict-mvar/LICENSE
  strict-mvar/NOTICE
  strict-mvar/README.md
  strict-mvar/src/Control/Concurrent/Class/MonadMVar/Strict.hs
  strict-mvar/strict-mvar.cabal
  strict-stm/README.md
  strict-stm/strict-stm.cabal
Labels: enhancement

#81 coot/timeout fix
  io-sim/src/Control/Monad/IOSim/Internal.hs
  io-sim/src/Control/Monad/IOSimPOR/Internal.hs
  io-sim/test/Test/Control/Monad/IOSim.hs
  io-sim/test/Test/Control/Monad/IOSimPOR.hs
Labels: bug

#83 github actions: download stylish-haskell
  .github/workflows/haskell.yml
Labels: CI
